version: "3.9"
services:
  redis-cache:
    container_name: 
      redis-cache
    image: redis
    ports:
      - "9001:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/redis.conf
    command: "redis-server redis.conf"
volumes:
    redis_data:
    