version: "3.9"
name: eventer-tools
services:
  admin-db:
    image: postgres:16.1-bullseye
    container_name: eventer-admin-db
    ports:
      - "9003:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./tools/docker/pgdata_admin:/var/lib/postgresql/data

  user-db:
    image: postgres:16.1-bullseye
    container_name: eventer-user-db
    ports:
      - "9005:5432"
    env_file:
      - .env
    volumes:
      - ./tools/docker/pgdata_user:/var/lib/postgresql/data

  redis-cache:
    container_name:
      redis-cache
    image: redis
    ports:
      - "9001:6379"
    volumes:
      - ./tools/docker/redis_data:/data
    command: "redis-server redis.conf"

  rabbitmq:
    image: rabbitmq:3.13.0-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_config:/etc/rabbitmq
volumes:
    redis_data:
    pgdata:
    rabbitmq_data:
    rabbitmq_config:
