version: "3.9"
name: redis-tools
services:
  redis-cache:
    container_name: 
      redis-cache
    image: redis
    ports:
      - "9001:6379"
    volumes:
      - ./tools/docker/redis_data:/data
    command: "redis-server redis.conf"
volumes:
    redis_data:
    