version: "3.9"
name: eventer-tools
services:
  admin-db:
    image: postgres:16.1-bullseye
    container_name: eventer-admin-db
    ports:
      - "9003:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./tools/docker/postgres_data:/var/lib/postgresql/data
  redis-cache:
    container_name: 
      redis-cache
    image: redis
    ports:
      - "9001:6379"
    volumes:
      - ./tools/docker/redis_data:/data
    command: "redis-server redis.conf"
volumes:
    redis_data:
    